src/Omega.Web/Models/TextFileModel.cs
using System.Collections.Generic;
using Omega.Client;
using Omega.Client.Memory;

namespace Omega.Web.Models
{
    public class TextFileModel
    {
        public string Label { get; set; }
        public string Description { get; set; }
        
        public int MaxLength { get; set; }
        
        public List<TextFileLineModel> Lines { get; set; }

        public TextFileModel()
        {
            Lines = new List<TextFileLineModel>();
        }
    }

    public class TextFileLineModel
    {
        public string Text { get; set; }

        public DisplayPosition Position { get; set; }
        public DisplayMode DisplayMode { get; set; }
        public SpecialMode SpecialMode { get; set; }
        public SpecialGraphic SpecialGraphic { get; set; }
    }
}

src/Omega.Web/Controllers/TextController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Omega.Web.Models;
using Omega.Web.Services;

namespace Omega.Web.Controllers
{
    public class TextController : Controller
    {
        private readonly ITestService testService;

        public TextController(ITestService testService)
        {
            this.testService = testService;
        }

        //
        // GET: /Text/

        public ActionResult Index()
        {
            return View(new List<TextFileModel> {
                //new TextFileModel { Label = 'A', Text = "Testing" }
            });
        }

        //
        // GET: /Text/Details/5

        public ActionResult Details(string label)
        {
            return View();
        }

        //
        // GET: /Text/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Text/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Text/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Text/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Text/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Text/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Omega.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>OmegaWeb</h1>
            </div>

            <div id="logindisplay">
                @if(Request.IsAuthenticated) {
                    <text>Welcome <b>@Context.User.Identity.Name</b>!</text>
                }
            </div>

            <nav>
                @Html.ActionLink("Text Files", "Index", "Text")
            </nav>
                
        </div>

        <div id="main">
            @RenderBody()
            <footer>
                This is the footer.
            </footer>
        </div>
    </div>
</body>
</html>

src/Omega.Web/Views/Text/Index.cshtml
@using Omega.Web.Models
@model List<TextFileModel>
@{
    ViewBag.Title = "Text Files";
    var grid = new WebGrid(Model, new[] { "Label", "Text" });
}

@grid.GetHtml(
    columns: grid.Columns(
        grid.Column("Label"),
        grid.Column("Text")
    )
)